//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TgSeeker.Cli.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TgSeeker.Cli.Locale.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API ID invalid..
        /// </summary>
        public static string API_ID_INVALID {
            get {
                return ResourceManager.GetString("API_ID_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This API id was published somewhere, you can&apos;t use it now..
        /// </summary>
        public static string API_ID_PUBLISHED_FLOOD {
            get {
                return ResourceManager.GetString("API_ID_PUBLISHED_FLOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is running....
        /// </summary>
        public static string App_State_Running {
            get {
                return ResourceManager.GetString("App_State_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many requests.
        /// </summary>
        public static string Auth_Error_TooManyRequests {
            get {
                return ResourceManager.GetString("Auth_Error_TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the authorization process..
        /// </summary>
        public static string AUTH_RESTART {
            get {
                return ResourceManager.GetString("AUTH_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone number.
        /// </summary>
        public static string Auth_State_EnterPhoneNumber {
            get {
                return ResourceManager.GetString("Auth_State_EnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization error.
        /// </summary>
        public static string Auth_State_Fail {
            get {
                return ResourceManager.GetString("Auth_State_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization required.
        /// </summary>
        public static string Auth_State_Required {
            get {
                return ResourceManager.GetString("Auth_State_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization complete.
        /// </summary>
        public static string Auth_State_Success {
            get {
                return ResourceManager.GetString("Auth_State_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number validation required.
        /// </summary>
        public static string Auth_State_ValidationRequired {
            get {
                return ResourceManager.GetString("Auth_State_ValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter code.
        /// </summary>
        public static string Auth_State_WaitForCode {
            get {
                return ResourceManager.GetString("Auth_State_WaitForCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature is not supported.
        /// </summary>
        public static string FeatureNotSupported {
            get {
                return ResourceManager.GetString("FeatureNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone_code is missing..
        /// </summary>
        public static string PHONE_CODE_EMPTY {
            get {
                return ResourceManager.GetString("PHONE_CODE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone code you provided has expired..
        /// </summary>
        public static string PHONE_CODE_EXPIRED {
            get {
                return ResourceManager.GetString("PHONE_CODE_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided phone code is invalid..
        /// </summary>
        public static string PHONE_CODE_INVALID {
            get {
                return ResourceManager.GetString("PHONE_CODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t sign up using this app..
        /// </summary>
        public static string PHONE_NUMBER_APP_SIGNUP_FORBIDDEN {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_APP_SIGNUP_FORBIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided phone number is banned from telegram..
        /// </summary>
        public static string PHONE_NUMBER_BANNED {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_BANNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You asked for the code too many times..
        /// </summary>
        public static string PHONE_NUMBER_FLOOD {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_FLOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is invalid..
        /// </summary>
        public static string PHONE_NUMBER_INVALID {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is not yet being used..
        /// </summary>
        public static string PHONE_NUMBER_UNOCCUPIED {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_UNOCCUPIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have tried logging in too many times..
        /// </summary>
        public static string PHONE_PASSWORD_FLOOD {
            get {
                return ResourceManager.GetString("PHONE_PASSWORD_FLOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone is password protected..
        /// </summary>
        public static string PHONE_PASSWORD_PROTECTED {
            get {
                return ResourceManager.GetString("PHONE_PASSWORD_PROTECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure while signing in..
        /// </summary>
        public static string SIGN_IN_FAILED {
            get {
                return ResourceManager.GetString("SIGN_IN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating the SMS code..
        /// </summary>
        public static string SMS_CODE_CREATE_FAILED {
            get {
                return ResourceManager.GetString("SMS_CODE_CREATE_FAILED", resourceCulture);
            }
        }
    }
}
